[[CeresCApi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26dd1d58ad035e6aa1256f548679fcb977b3e9e5"
libc = "glibc"
os = "linux"

    [[CeresCApi.download]]
    sha256 = "ddc838d0cf51435893ad6f24d48340286dabeb43f0284d913d1c6bbfd2913c2b"
    url = "https://github.com/gzhang8/CeresCApi_jll.jl/releases/download/CeresCApi-v0.1.0+0/CeresCApi.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[CeresCApi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d89e0e320cae74b1943beb3b341cb4d023a22fd"
libc = "glibc"
os = "linux"

    [[CeresCApi.download]]
    sha256 = "42588cb507d3f7e630b9e528e6bc9962dbc8122b80431cca76670958a569f451"
    url = "https://github.com/gzhang8/CeresCApi_jll.jl/releases/download/CeresCApi-v0.1.0+0/CeresCApi.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
